# Generated by Django 5.1.6 on 2025-02-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the configuration.', max_length=255)),
                ('database_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB')], default='postgresql', help_text='Select the type of database.', max_length=20)),
            ],
            options={
                'db_table': 'generator_configurations',
            },
        ),
    ]
